## 영상정보처리 3주차 과제 템플리트
이름: 이상민            
학번: 32153180

구글 드라이브를 연결하고 자신의 노트북이 저장되어 있는 폴더로 이동하시오

In [1]:
from google.colab import drive 
drive.mount('/gdrive')

Mounted at /gdrive


In [4]:
%cd /gdrive/My\ Drive/ImageProcClass/Week3
%ls

/gdrive/My Drive/ImageProcClass/Week3
2020-2-ImgProc-HW3-이상민-32153180.ipynb  2020_2_ImgProc_HW3_Template.ipynb


다음에 이미지 경로 '../Dongkeun-OpenCV-ImgData/logo.png' 를 변경하지 말고 이미지를 읽고, 해당 이미지에 대한 type, size, dtype 등의 속성을 체크하시오. 

In [6]:
import cv2

img = cv2.imread('../Dongkeun-OpenCV-ImgData/logo.png')
print('image type : {}'.format(type(img)))
print('image size : {}'.format(img.size))
print('image dtype : {}'.format(img.dtype))

image type : <class 'numpy.ndarray'>
image size : 876600
image dtype : uint8


다음의 셀에 읽은 이미지에서 좌표 y = 100, x = 50 에 있는 화소의 각 색요소 값을 한번에 읽어 출력하시오. 또한 각 색요소의 값을 별도로 가져오는 예를 작성하시오.

In [8]:
(b, g, r) = img[100, 50]
print('(b, g, r) :', b, g, r)

blue = img[100, 50, 0]
green = img[100, 50, 1]
red = img[100, 50, 2]
print('blue : {}, green : {}, red : {}'.format(blue, green, red))

(b, g, r) : 0 0 0
blue : 0, green : 0, red : 0


다음의 셀에 읽은 이미지에서 좌표 y = 100, x = 50 의 화소를 순수 녹색(green) 으로 세팅하는 코드를 작성하고 해당 분야를 ROI 를 이용해 확대해서 출력하시오. 

In [9]:
import matplotlib.pyplot as plt

img[100, 50] = (0, 255, 0)
ROI = img[90:110, 40:60]
plt.imshow(ROI)
plt.show()

## Accessing and Manipulating pixels in opencv with grayscale images

위에서 사용한 동일 입력 이미지를 읽어서 matplotlib.pyplot에 맞는 채널 순서로 변환하고 본래 이미지와 변환된 이미지를 matplotlib.pyplot 을 이용하여 출력하시오. 


In [19]:
b, g, r = cv2.split(img)
plt_img = cv2.merge([r, g, b])

plt.subplot(121)
plt.imshow(img)
plt.subplot(122)
plt.imshow(plt_img)
plt.show()

## In Depth Example
강의노트 'In Depth' 부분에 있는 예제를 임의의 값을 이용하여 예시하고 간단한 설명을 붙여 자기 노트를 완성하시오. 

### What is Numpy ?
Numpy는 <code>Numerical Python</code>의 줄임말로 벡터 및 행렬 연산에 있어 편리한 기능을 제공한다.

In [11]:
# module import
import numpy as np

0-Dimensional array

In [12]:
arr = np.array(7)
print('0-D array :', arr)
print('0-D array shape :', arr.shape)

0-D array : 7
0-D array shape : ()


1-Dimensional array

In [13]:
arr = np.array([4.1, 3, -8.5, 0.9])
print('1-D array :', arr)
print('1-D array shape :', arr.shape)

1-D array : [ 4.1  3.  -8.5  0.9]
1-D array shape : (4,)


2-Dimensional array

In [14]:
arr = np.array([[100, 50, 75],
                [45, 78, 10],
                [32, 45, 97],
                [7, 56, 88]])
print('2-D array :', arr)
print('2-D array shape :', arr.shape)

2-D array : [[100  50  75]
 [ 45  78  10]
 [ 32  45  97]
 [  7  56  88]]
2-D array shape : (4, 3)


3-Dimensional array

In [15]:
arr = np.array([[[5.2, 4.8],
                 [8.1, 9.7]],
                [[0.3, 0.8],
                 [8.2, 6.6]]])
print('3-D array :', arr)
print('3-D array shape :', arr.shape)

3-D array : [[[5.2 4.8]
  [8.1 9.7]]

 [[0.3 0.8]
  [8.2 6.6]]]
3-D array shape : (2, 2, 2)


practice

| | Exam 1 | Exam 2 |
| -- | -- | -- |
| Ashley | 93 | 95 |
| Brad | 84 | 100 |
| Cassie | 99 | 87 |

In [16]:
grade = np.array([93, 95, 84, 100, 99, 87])

# slicing
print('slice 95~99 :', grade[1:5])

# reverse
print('reverse :', grade[::-1])

# 차원 변경 (1차원 -> 2차원)
print('1-D shape :', grade.shape)
new_grade = grade.reshape(3, 2)
print('2-D shape :', new_grade.shape)
print(new_grade)

# show Brad Exam2 score
print('Brad Exam2 score :', new_grade[1, 1])

# show Cassie Exam1, Exam2 score
print('Cassie score :', new_grade[2, :])

# show Exam1 score
print('Exam score :', new_grade[:, 0])

slice 95~99 : [ 95  84 100  99]
reverse : [ 87  99 100  84  95  93]
1-D shape : (6,)
2-D shape : (3, 2)
[[ 93  95]
 [ 84 100]
 [ 99  87]]
Brad Exam2 score : 100
Cassie score : [99 87]
Exam score : [93 84 99]
